# _config.yml
<<<<<<< HEAD
title: Le site de JIJI
description: "Un site GitHub Pages avec un joli thème"
theme: hacker

=======
title: Mon site
description: "Un site GitHub Pages avec un joli thème"
theme: minima
>>>>>>> 4b55a4950a98e6cd80257382badca8b7169a3705
